apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-configmap
data:
  IP_SISTEMA: http://localhost:30001

---

apiVersion: v1
kind: Service
metadata: 
  name: svc-portal-noticias
spec:
  type: NodePort
  ports: 
    - port: 80
      #targetPort: 80
      nodePort: 30000
  selector:
    app: portal-noticias

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec: 
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: portal-noticias
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe: 
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15 
            periodSeconds: 30
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: portal-configmap
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias
